### ISSUE TITLE
No option to cancel 

### ISSUE THREAD

**Issue by bhamde** [darrenfang/vuetify-datetime-picker#10]
Cannot 'Cancel' or go out of the Modal once you are in.

Would be good to have a Cancel Option

**Comment by max3163** [comment]
Yes, must have option !

+1

**Comment by darrenfang** [comment]
@bhamde @max3163 Click 'CLEAR' button

**Comment by bhamde** [comment]
@darrenfang 'CLEAR' does not cancel what you have entered and keeps the old values, it clears the date/time  to null!

**Comment by bhamde** [comment]
Why is that closed? Sorry, I don't think they are the same functionality @darrenfang

**Comment by darrenfang** [comment]
@bhamde See Commit 97f1aa7e1eff3a470b51bf694a7e75842fdfa90d

**Comment by runtangr** [comment]
@bhamde 
you can use `actions`, override button.
![l_62558942_320_1c8301d7acfa2e2469f0790051a198a3](https://user-images.githubusercontent.com/20644165/225576412-b39dad48-9afb-4feb-a8c7-004074e60968.png)

use v-slot, use parent method, it can realize cancel(restore datetime).
https://github.com/darrenfang/vuetify-datetime-picker/blob/f9220b8acdd794edea9f0412a8c48b77635b3ae0/src/app.vue#L80-L83
![l_62558942_319_0308cd73c13303978334afffd487d523](https://user-images.githubusercontent.com/20644165/225575860-b2147654-2f81-4dc7-82ff-fb7c45f3c075.png)

just a little code. like this.
```html
<v-btn color="grey lighten-1" text @click.native="cancel(parent)">cancel</v-btn>
```
```js
cancel(parent) {
      parent.init(); // this is restore datetime
      parent.okHandler();
    },
```
