### ISSUE TITLE
Error when installing in vite project

### ISSUE THREAD

**Issue by Mosaab-Emam** [darrenfang/vuetify-datetime-picker#104]
### Problem:

If the package is installed in a project using vite instead of vue/cli, the following error arises when starting the dev server:
```
✘ [ERROR] Could not resolve "./components/DatetimePicker"

    node_modules/vuetify-datetime-picker/src/index.js:26:27:
      26 │ import DatetimePicker from './components/DatetimePicker'
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Environment details:

- OS: Linux
- Node version: 16.13.1
- Vue version: 2.6.11
- Vite version: 2.5.4

**Comment by sureshvv** [comment]
You need to specidy the .vue extension.

Try to change it as follows:

    import DatetimePicker from './components/DatetimePicker.vue'

**Comment by Mosaab-Emam** [comment]
Thanks for the clarification.
I might not be able to test this myself as it is not relevant to me anymore, but it is much appreciated none the less.
Will be closing this issue.
