### ISSUE TITLE
Let developer provide custom icons

### ISSUE THREAD

**Issue by Shinigami92** [darrenfang/vuetify-datetime-picker#13]
- https://github.com/darrenfang/vuetify-datetime-picker/blob/master/src/components/DatetimePicker.vue#L20
- https://github.com/darrenfang/vuetify-datetime-picker/blob/master/src/components/DatetimePicker.vue#L23

I use Font Awesome in my project and dont want Material Icons
Let us provide other icons like `far fa-calendar`

**Comment by justin-nodeboy** [comment]
Added a PR for this. #14

**Comment by darrenfang** [comment]
@justin-nodeboy @Shinigami92 You can use `dateSlot` and `timeSlot` to custom icons. Fixed  6825df754b1b6462d43191008fe840075648495f.
