### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by msdavid1296** [darrenfang/vuetify-datetime-picker#16]
It works fine for me in local. But creating build and when I deploy it live it does not work properly.
![screenshot from 2019-02-02 11-51-56](https://user-images.githubusercontent.com/40631784/52160933-f6b50180-26e3-11e9-85f6-8150cc65284f.png)
![screenshot from 2019-02-02 11-56-49](https://user-images.githubusercontent.com/40631784/52160934-f6b50180-26e3-11e9-878a-fdcb20c953de.png)

In live, I get some warnings in my local

**Comment by darrenfang** [comment]
Maybe cause by other style sheets.

**Comment by gmarineau** [comment]
Hi have the same issue

**Comment by gmarineau** [comment]
I have found a solution if you put this on the "main.js" file

`import 'vuetify/dist/vuetify.min.css';`
