### ISSUE TITLE
"Event Access_time" panel?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [darrenfang/vuetify-datetime-picker#22]
I just attempted to use this component and for some reason it has a panel at the top with what appear to be buttons or links that do nothing but are labelled "Event" and "Access_time" and are causing a scroll bar to appear to the right.

What are these and how do I remove them?

**Comment by WhatFreshHellIsThis** [comment]
Ahh...I see what is happening, this component assumes a certain icon set is being used.  I don't use that icon set.

**Comment by jextrevor** [comment]
@WhatFreshHellIsThis Did you figure out a solution to this? I'm having the same problem. Trying to avoid having to make a fork of this project.

**Comment by WhatFreshHellIsThis** [comment]
Yes, I ran into multiple other issues and ended up writing my own composite control which was surprisingly easier than I expected using the stock vuetify date and time pickers together.
