### ISSUE TITLE
Using custom display format completely breaks the picker

### ISSUE THREAD

**Issue by charliegilmanuk** [darrenfang/vuetify-datetime-picker#23]
I would like to use the `format` prop to manipulate what the displayed datetime in the input looks like:
`ddd D MMMM YYYY, HH:mm"`

This works fantastic, until I click the input to bring up the picker and the value is way out, the picker displays (and outputs) completely obscure dates, e.g. `2000-01-10 00:00:00`.  

Some examples:
input:  `2018-03-31 10:00:00`
Output:  `2000-01-10 00:00`
Desired:  Mon 31 March 2018, 10:00

Input:  `2018-06-18 16:45:00`
Output:  `2030-01-20 00:00:00`
Desired:  Mon 18 June 2018, 16:45

Struggling to find any correlation between these results, but my thought was that the plugin should be parsing the raw value in the v-model rather than the formatted value for the text box?

**Comment by darrenfang** [comment]
You can try this code:

```javascript
<template>
    <v-app dark>
        <v-container>
            <v-layout row justify-center>
                <v-flex xs4>
                    <v-datetime-picker v-model="datetime" format="ddd D MMMM YYYY, HH:mm"></v-datetime-picker>
                </v-flex>
            </v-layout>
            <v-layout row justify-center>
                <v-flex xs4>
                    <v-btn @click="btnHandler">Show Date</v-btn>
                </v-flex>
            </v-layout>
        </v-container>
    </v-app>
</template>

<script>
  export default {
    data () {
      return {
        datetime: new Date()
      }
    },
    methods: {
      btnHandler () {
        alert(this.datetime)
      }
    }
  }
</script>
```

**Comment by charliegilmanuk** [comment]
That's working perfectly as intended, thanks Darren.  Should I be parsing all my date strings as a `new Date()` in that case?

**Comment by charliegilmanuk** [comment]
```javascript
startDateTime: {
      get() {
        return moment(this.visit.Start).toDate();
      },
      set(val) {
        this.visit.Start = val;
      }
    },

    finishDateTime: {
      get() {
        return moment(this.visit.Finish).toDate();
      },
      set(val) {
        this.visit.Finish = val;
      }
    }
```

Using a computed getter/setter and parsing using `moment().toDate()` works.

**Comment by darrenfang** [comment]
try the latest version `2.1.0`
