### ISSUE TITLE
Doesn't work. None of the component render

### ISSUE THREAD

**Issue by douglasg14b** [darrenfang/vuetify-datetime-picker#26]
When using this I get these errors that seem to not be able to find any Vuetify components. Yet Vuetify is working just fine in my application.

If I copy/paste the component from github it does work. Albeit never updates the text field value until something else is clicked on, which is annoying.

![image](https://user-images.githubusercontent.com/1400380/56776805-055f0200-6783-11e9-979c-7f0e202d16f0.png)

**Comment by acyuta** [comment]
The same problem:

> "vuetify": "^1.5.5",
    "vuetify-datetime-picker": "^1.0.13",
    "vue": "^2.6.10",

Works on:

> "vuetify": "^1.3.14",
    "vuetify-datetime-picker": "^1.0.13",
    "vue": "^2.5.9",

**Comment by darrenfang** [comment]
@douglasg14b @acyuta Maybe this cause by `vuetify-loader` plugin. You can register components like this:

```javascript
import Vue from 'vue'
import Vuetify, {
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VDatePicker,
  VDialog,
  VIcon,
  VLayout,
  VProgressLinear,
  VSnackbar,
  VSpacer,
  VTab,
  VTabItem,
  VTabs,
  VTextarea,
  VTextField,
  VTimePicker
} from 'vuetify/lib'

Vue.use(Vuetify, {
  components: {
    VTextField,
    VProgressLinear,
    VSnackbar,
    VLayout,
    VDialog,
    VCard,
    VCardTitle,
    VCardActions,
    VSpacer,
    VBtn,
    VTextarea,
    VCardText,
    VTabs,
    VTab,
    VIcon,
    VTabItem,
    VDatePicker,
    VTimePicker
  }
})
```

**Comment by douglasg14b** [comment]
@darrenfang  I'm importing all of vuetify already.

This issue only presents itself when your library is added to the project... why close the issue?

**Comment by dyardyGIT** [comment]
Yes I had same issue and found partial resolution when changing in vuetify.js
**This worked**
import Vue from 'vue'
//import Vuetify from 'vuetify/lib'
import Vuetify from 'vuetify'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',
})

**This did NOT work**
import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',
})

The issue was the first time i clicked on the control/component it took 10 seconds to open up.  Too slow.  Something is not right here

**Comment by jwieneke** [comment]
Having the same issue.
Got that errors just after adding this library.
It's working in another project for me, so maybe there are some side effects between different versions of dependencies, but I could not figure out which quickly.
I guess, this should be fixed. Changing `vuetify.js` doesn't seem to be a solution for me.

**Comment by darrenfang** [comment]
@douglasg14b @acyuta @dyardyGIT @jwieneke 

Need a devDependencies of `@nuxtjs/vuetify@0.5.7` when use `vuetify@1.5.x`

```shell
yarn add -D  @nuxtjs/vuetify@0.5.7
```

Modify `nuxt.config.js`:

```js
  devModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/vuetify'
  ]
```

More information: [Module for Vuetify 1.5.x](https://github.com/nuxt-community/vuetify-module/tree/0.x)

**Comment by joshuagamboa** [comment]
Raised a simple PR for this. Hope it helps others.

**Comment by Calvido** [comment]
> @douglasg14b @acyuta @dyardyGIT @jwieneke
> 
> Need a devDependencies of `@nuxtjs/vuetify@0.5.7` when use `vuetify@1.5.x`
> 
> ```shell
> yarn add -D  @nuxtjs/vuetify@0.5.7
> ```
> 
> Modify `nuxt.config.js`:
> 
> ```js
>   devModules: [
>     // Doc: https://github.com/nuxt-community/eslint-module
>     '@nuxtjs/vuetify'
>   ]
> ```
> 
> More information: [Module for Vuetify 1.5.x](https://github.com/nuxt-community/vuetify-module/tree/0.x)

Hi, i try to get run this with vuetify-dattime-picker versión legacy and vuetify 1.5.14, your suggestion to add dev dependency @nuxtjs/vuetify@0.5.7 its for all case? because  i don't use nuxt and this don't work adding only this dev dependency, stile the same error, please help me understand that and how i can put this to work in my project

**Comment by darrenfang** [comment]
@Calvido Try the version `1.1.3`

**Comment by Calvido** [comment]
> @Calvido Try the version `1.1.3`

thanks men, i try the new 1.1.3, now this error with the vuetify 1.5.x components it´s gone but now receive console error with the vuetify-datetime-picker properties, I define the simple way 
`<v-datetime-picker v-model="datetime"></v-datetime-picker>`

And get error on every property of the components like this: 

> Property or method "width" is not defined on the instance but referenced during render.
> Property or method "errorMessages" is not defined on the instance but referenced during render.
> Property or method "errorCount" is not defined on the instance but referenced during render.
...
> Property or method "appendIcon" is not defined on the instance but referenced during render.
> Property or method "prependIcon" is not defined on the instance but referenced during render.

I need define and set values in all properties?
