### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by devsarmico** [darrenfang/vuetify-datetime-picker#29]
Please provide a live demo link in the README.md

**Comment by darrenfang** [comment]
Checkout the code, and run `yarn dev`

**Comment by darrenfang** [comment]
This is the live demo https://darrenfang.github.io/vuetify-datetime-picker/

**Comment by ironshashi** [comment]
Can we have the source code of the demo?

**Comment by darrenfang** [comment]
@ironshashi https://github.com/darrenfang/vuetify-datetime-picker/blob/master/src/app.vue
