### ISSUE TITLE
how to select seconds ?

### ISSUE THREAD

**Issue by ironshashi** [darrenfang/vuetify-datetime-picker#31]
In the current version, I can only select the hours and minutes and my place for seconds in 00, How do I select the seconds also? 
And how I can call a custom method on click of save button?

**Comment by darrenfang** [comment]
Set the property `useSeconds` to `true`.

**Comment by ironshashi** [comment]
@darrenfang  I am still getting seconds 00

**Comment by darrenfang** [comment]
@ironshashi upgrade to latest version, `1.1.2` or `2.0.3`.

**Comment by ironshashi** [comment]
@darrenfang Thank you so much

**Comment by ironshashi** [comment]
@darrenfang I am facing one more problem in this, which is,  in my text field I have date and time like this 2020-02-01,12:05:20 but when I open the dialog it shows calendar for august-2019 and time is also 00:00:00, how can i pre select the date and time in modal?
