### ISSUE TITLE
 Could not install from "vuetify-datetime-picker\src\stylus\main.styl" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by ranganayakulunakka** [darrenfang/vuetify-datetime-picker#33]
how to  install "vuetify-datetime-picker\src\stylus\main.styl" as it does not contain a package.json file.

**Comment by darrenfang** [comment]
this file contains in package `vuetify-datetime-picker`, just `npm install vuetify-datetime-picker`, and the file path is `vuetify-datetime-picker/src/stylus/main.styl`. And you should configure `stylus-loader` in the `webpack.config.js`
