### ISSUE TITLE
Unknown custom element: <v-dialog>

### ISSUE THREAD

**Issue by Anubarak** [darrenfang/vuetify-datetime-picker#34]
I included your datetime-picker into my project with Vuetify >2.0

While I can use the default date and time pickers without any issues I always receive the following error when I try to use your library
```
[Vue warn]: Unknown custom element: <v-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option
```

I use `v-dialog` by myself without any issues but it seems to break in your library. Is there anything I can do?

**Comment by darrenfang** [comment]
It maybe cause by the ` vuetify-loader` plugin. Configure this in `webpack.config.js`: https://vuetifyjs.com/en/customization/a-la-carte

If you use the `nuxt.js`, you can configure `vuetify-module` in `nuxt.config.js`: https://github.com/nuxt-community/vuetify-module, and don't need ` vuetify-loader`.

**Comment by Anubarak** [comment]
I was not able to fix it so I forked the included Vuetify and the components in it and added full moment support.
Then it worked

Thank you very much - it's a great help
