### ISSUE TITLE
v-model doesn't update the displayed value with Vuetify 2

### ISSUE THREAD

**Issue by alexcomo95** [darrenfang/vuetify-datetime-picker#43]
I have Vuetify 2.1.0. Assigning a model to the component updates the datetime prop, but the input field won't update. In other words, the data ('date' and 'time') is not updating when the v-model's related variable changes.

For a bit of context, here is a simple example of how I use the picker:
```
<template>
  <v-datetime-picker
    v-model="event.start"
    label="Start"
  ></v-datetime-picker>
</template>

<script>
export default {
  data: () => ({
    event: {
      start: null
    }
  })
}
```
Modifying 'event.start' won't update the data in the picker.

The reason I need this is because the picker is in a form that is only shown once the user clicks a date in a calendar. They can create events and that field is filled for them, making things easier. That means I should be able to change its value from the parent component after the picker is created. This is something that used to work when I used Vuetify ^1.5.5. Probably because it was destroying the picker.

For now, all I can do is using v-if so the picker is destroyed once my dialog closes. And is created again when the form opens. I hoped there would be something more efficient and intuitive.

**Comment by raphael-jolimoi** [comment]
You can also add a :key with the date to force update.

`            <v-datetime-picker
              label="Date"
              v-model="booking.start_date"
              :key="booking.start_date"
            >
            </v-datetime-picker>`

**Comment by kafenio** [comment]
@raphael-jolimoi that proposed workaround does not work with vue2 + vuetifyjs 2.1.0. you have to watch the property, otherwise the prop is not updated.

**Comment by darrenfang** [comment]
Working on it.
