### ISSUE TITLE
Translation issue on timepicker (nuxt.js)

### ISSUE THREAD

**Issue by Nks** [darrenfang/vuetify-datetime-picker#44]
![image](https://user-images.githubusercontent.com/349293/66121897-f6f4fc00-e5e6-11e9-83e6-6e06e25a5964.png)

yarn version: 1.16.0
nuxt.js: 2.9.2

On dev mode translation showing correct. After building application translation showing incorrect.

**Comment by darrenfang** [comment]
I'm not sure. Can you give me some demo code?

**Comment by Nks** [comment]
I am using pug, but same problem without it:
```
v-datetime-picker(:label="$t('start_date')" v-model="startDateTime"
                            :text-field-props="{prependIcon: 'access_time', error: form.errors.has('start_date'), errorMessages: form.errors.has('start_date') ? form.errors.get('start_date') : []}"
                            date-format="MM/dd/yyyy" time-format="hh:mm aa")
```

Here my `plugins/vuetify-datetime-picker.js`:

```
import Vue from 'vue'
import DatetimePicker from 'vuetify-datetime-picker'

Vue.use(DatetimePicker)
```

And nuxt.js config injection:
```
plugins: [
   ....
    { src: '~plugins/vuetify-datetime-picker', mode: 'client' },
   ....
  ],
```

Configuration of i18n:
```
import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

const i18n = new VueI18n({
  locale: 'en',
  messages: {}
})

export default async ({ app, store }) => {
  if (process.client) {
    await loadMessages(store.getters['lang/locale'])
  }

  app.i18n = i18n
}

/**
 * @param {String} locale
 */
export async function loadMessages (locale) {
  if (Object.keys(i18n.getLocaleMessage(locale)).length === 0) {
    const messages = await import(/* webpackChunkName: "lang-[request]" */ `~/lang/${locale}`)
    i18n.setLocaleMessage(locale, messages)
  }

  if (i18n.locale !== locale) {
    i18n.locale = locale
  }
}
```

Vuytify Timepicker works perfect with translations, but this plugin works odd.

**Comment by Nks** [comment]
![image](https://user-images.githubusercontent.com/349293/67054815-6e31a080-f14e-11e9-945c-7d6d00cb5d83.png)
Here default v-time-picker component

And here I opened the v-datetime-picker:

![image](https://user-images.githubusercontent.com/349293/67054869-a33df300-f14e-11e9-95dc-630bf47f7354.png)

Here console:
![image](https://user-images.githubusercontent.com/349293/67054887-b486ff80-f14e-11e9-9ea6-19eebb32e5f2.png)

**Comment by kafenio** [comment]
problem is probably, that this commit https://github.com/darrenfang/vuetify-datetime-picker/pull/46/commits/7be858c2f80ad6314950b9f93da94dd629af9bf8 from my pull request was not included. the vuetify timePicker does not render the properties properly.

**Comment by Nks** [comment]
@kafenio I think problem that I used buildModules and `'@nuxtjs/vuetify',` instead of connect it as plugin. Added this to the plugins:
```
import '@mdi/font/css/materialdesignicons.css'
import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'

Vue.use(Vuetify)

export default ctx => {
  const vuetify = new Vuetify({
    theme: {
      dark: true,
    },
    icons: {
      iconfont: 'mdi',
    },
  })

  ctx.app.vuetify = vuetify
  ctx.$vuetify = vuetify.framework
}
```

And added it before datetimepicker component and it looks like problem solved. I'll confirm shortly.

**Comment by Nks** [comment]
Confirmed. Problem can be solved in this way.
