### ISSUE TITLE
Not supporting validations.

### ISSUE THREAD

**Issue by shenba1296** [darrenfang/vuetify-datetime-picker#7]

**Comment by WhatFreshHellIsThis** [comment]
Tried to use with v-validate but it ignores it as if it's not even set.  This is a required feature for many people who need a date and time input.

**Comment by joshuagamboa** [comment]
It supports "errorMessages" and error related properties like any regular vuetify v-input. You can easily write a method to validate your input. Then probably add a watch on the model to trigger said method.

**Comment by bchellingworth** [comment]
I had to ditch this component because of the lack of validation and also other vuetify inpout props dont work like hints etc

**Comment by forgivegod** [comment]
@bchellingworth 

try using `text-field-props` and vee,  here is an example

 ```
<validation-provider v-slot="{ errors }" name="SomeName" rules="required|max:10">
  <v-datetime-picker v-model="datetime"
    :text-field-props="{
      errorMessages: errors,
      outlined:true,
      class:'custom-label-color',
      prependIcon:'mdi-clock-start',
    }"
  />
</validation-provider>
```

To get the above working see the Vuetify doc examples for vee-validate here: https://vuetifyjs.com/en/components/forms/#vee-validate
