### ISSUE TITLE
Time Defaults To Previous Hour When Minutes Is Not Selected

### ISSUE THREAD

**Issue by piperRyan** [darrenfang/vuetify-datetime-picker#8]
How to reproduce: 
- Select a day on the calender. 
- Select a hour
- Select a minute
- Repeat the first two steps, but in the second step choose a different hour
- Don't select minute and just hit ok. 

Expected Results: 
 - The hour value should have been updated to the new hour value. 

Actual Outcome: 
- The hours value stayed the same as the previous input. 

Admittedly, this may be an upstream bug somewhere in the timepicker component.

**Comment by richardcornelissen** [comment]
I think I found the source of the bug. At https://github.com/darrenfang/vuetify-datetime-picker/blob/master/src/components/DatetimePicker.vue#L142 it specifically ignores the selection of the hours and only changes the value upon also selecting the minutes
